package ru.gr0946x.net;

public enum MessageType {
    MESSAGE,
    INFO,
    REQUEST,
    ERROR,
    AUTH_REQUEST,
    AUTH_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    PRIVATE_MESSAGE,
    USER_LIST,
    HISTORY_REQUEST,
    HISTORY_RESPONSE,
    SEARCH_REQUEST,
    SEARCH_RESPONSE
}
